# Generated by Django 2.1.2 on 2018-12-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=50)),
                ('article_type', models.CharField(max_length=50)),
                ('article_headline', models.CharField(max_length=500)),
                ('article_discription', models.CharField(max_length=1000)),
                ('article_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ModeratorRegistration',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
