# Generated by Django 2.1.2 on 2018-12-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_headline', models.CharField(max_length=100)),
                ('article_dicription', models.CharField(max_length=500)),
            ],
        ),
    ]
