# Generated by Django 2.1.2 on 2018-12-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20181206_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashion',
            name='article_image',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health',
            name='article_image',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='article_image',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
