# Generated by Django 2.1.2 on 2018-12-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_auto_20181207_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModFashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_headline', models.CharField(max_length=100)),
                ('article_dicription', models.CharField(max_length=500)),
                ('article_image', models.FileField(upload_to='')),
                ('user_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_headline', models.CharField(max_length=100)),
                ('article_dicription', models.CharField(max_length=500)),
                ('article_image', models.FileField(upload_to='')),
                ('user_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_headline', models.CharField(max_length=100)),
                ('article_dicription', models.CharField(max_length=500)),
                ('article_image', models.FileField(upload_to='')),
                ('user_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Technology',
            new_name='HomeFashion',
        ),
        migrations.RenameModel(
            old_name='Health',
            new_name='HomeHealth',
        ),
        migrations.RenameModel(
            old_name='Fashion',
            new_name='HomeTechnology',
        ),
    ]
