# Generated by Django 2.1.2 on 2018-11-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserRegistration',
        ),
    ]
