# Generated by Django 2.1.2 on 2018-11-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20181130_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moderator',
            new_name='ModeratorRegistration',
        ),
    ]
