# Generated by Django 2.1.2 on 2018-12-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_auto_20181130_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyRegistration',
        ),
        migrations.DeleteModel(
            name='StudentRegistration',
        ),
    ]
